### ISSUE TITLE
Setting up File Watcher and LiveReload on Windows

### ISSUE THREAD

**Issue by mgroves** [couchbase/docs-site#105]
Step 3 in the readme seems to be Mac/Linux specific:

`$ LIVERELOAD=true gulp`

I'm not 100% sure what this translates to in Windows. Is LIVERELOAD an environment variable? Why is 'gulp' in there?

**Comment by jamiltz** [comment]
Yes, gulp is the toolchain to start a build, and LIVERELOAD=true tells gulp to refresh the browser tabs when the docs build is done. Following might work for Windows?

```
C:\> set LIVERELOAD=true
C:\> gulp
```

**Comment by jamiltz** [comment]
@mgroves does that work? Once we figure this out, I'll add it to the README.

**Comment by mgroves** [comment]
I guess so, except that I'm getting "No gulpfile found". Is this only supposed to work with a copy of the docs-site repo (I've been trying it on tutorials-contrib). If yes, will it somehow pull in the tutorials-contrib (and other satellite repos)?

**Comment by jamiltz** [comment]
Yes, you'll need a copy of `docs-site` and `tutorials-contrib`.
I've written some notes for how to setup the workspace specifically for tutorials https://docs.couchbase.com/tutorials/tutorial-template/sample.html#workspace
It'd be great to know how those work out, nobody has had a chance to test them out yet.
