### ISSUE TITLE
Use of the gulpfile in our Antora project

### ISSUE THREAD

**Issue by JakeSCahill** [couchbase/docs-site#708]
We are setting up an Antora project and looking for live reload functionality. We realised that this repo does not have a license, so we were wondering if we could get permission to use the gulpfile in this repo for our own project.

**Comment by osfameron** [comment]
Hi @JakeSCahill - I'll check what licence the repo should be under now!

Informally, to best of my understanding, as this is a Public repo that should be fine (we put code that we are NOT happy to be reused as opensource in Private repos)

**Comment by osfameron** [comment]
I'll update when I can, have also pinged you on 🌷 Zulip 😄

**Comment by osfameron** [comment]
https://github.com/couchbase/docs-site/blob/master/LICENSE is now updated, and there's a (slightly different, as it's mostly code from Antora default UI) license in docs-ui also 👍
